spark_master:
  image: lab41/spark-master
  hostname: "sparkmaster"
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
  volumes:
    - ./runtime/cdh5/hadoop/conf:/etc/hadoop/conf
    - ./runtime/cdh5/hive/conf:/etc/hive/conf

spark_worker:
  image: lab41/spark-worker
  links:
    - spark_master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 8081:8081
  environment:
    SPARK_MASTER: "spark://sparkmaster:7077"
  volumes:
    - ./runtime/cdh5/hadoop/conf:/etc/hadoop/conf
    - ./runtime/cdh5/hive/conf:/etc/hive/conf